### ISSUE TITLE
help pls. 

### ISSUE THREAD

**Issue by pesertakursustm** [saferwall/saferwall#171]
~/saferwall # make saferwall 
Makefile:18: /root/saferwall/.env: No such file or directory
make: *** No rule to make target '/root/saferwall/.env'.  Stop.

**Comment by LordNoteworthy** [comment]
@pesertakursustm 

I just pushed an example.env, You can rename it to .env, the initial reason why this file is not in git because it has AV license codes. Gimme some time, I will ease the process of deploying the app. In the meanwhile, you can play around this hosted version: saferwall.com.

**Comment by kiraitachi** [comment]
> @pesertakursustm
> 
> I just pushed an example.env, You can rename it to .env, the initial reason why this file is not in git because it has AV license codes. Gimme some time, I will ease the process of deploying the app. In the meanwhile, you can play around this hosted version: https://saferwall.com.

Hi! It still doesnt work.

I get the following message:

`aws configure
AWS Access Key ID [****************NKJA]:
AWS Secret Access Key [****************OGD1]:
Default region name [eu-west-1]:
Default output format [None]:
make[1]: Leaving directory '/home/kira/saferwall'
make aws-create-user
make[1]: Entering directory '/home/kira/saferwall'
aws iam create-group --group-name kops

An error occurred (InvalidClientTokenId) when calling the CreateGroup operation: The security token included in the requ
est is invalid.
make[1]: *** [build/mk/kops.mk:7: aws-create-user] Error 255
make[1]: Leaving directory '/home/kira/saferwall'
make: *** [build/mk/kops.mk:104: saferwall] Error 2`

**Comment by LordNoteworthy** [comment]
Hello @kiraitachi 

Thanks for feedback, let me take a look.

**Comment by kiraitachi** [comment]
Hi @LordNoteworthy 

I wouldnt put it in "enhancement" is more an error issue building, seems part of the code is in AWS...and the key token is invalid maybe trying to change it in the GitRepo and pushing the new token?

Try to go to the security credentials on your account page AWS: Click on your name in the top right corner -> My security credentials

Then generate access keys over there and use those access keys in your credentials file (aws configure)

Cheers!

**Comment by LordNoteworthy** [comment]
@kiraitachi 

I am sorry for late reply. That seems to be coming for AWS and auth somehow is failing.

Did you run:

# Because "aws configure" doesn't export these vars for kops to use, we export them now
export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)

I updated the example.env, can you make the AWS_XYZ values are set  correctly ?

I just verified from my end and the command worked fine.

**Comment by LordNoteworthy** [comment]
Closing this one :) Thanks @kiraitachi  for your feedback.
